<?php $data = $block->getEditData(); ?>
<?php //echo '<pre>'; print_r($data); die; ?>
<div id="custom-form">
   <form class="contact custom" 
         action="<?php echo $this->getUrl('crud/index/save', ['_secure' => true]);?>"
         id="custom-form"
         method="post"
         data-hasrequired="<?php  echo __('* Required Fields') ?>"
         data-mage-init='{"validation":{}}'>
 
        <fieldset class="fieldset">
            <legend class="legend"><span><?php  echo __("Contact") ?></span></legend><br />
            <div class="field name required">
                <label class="label" for="name"><span><?php  echo __('Name') ?></span></label>
                <div class="control">
                    <input name="name" id="name" title="<?php  echo __('Name') ?>" class="input-text" type="text" data-validate="{required:true}" value="<?php echo $data['name']; ?>"/>
                    <input type="hidden" name="editId" id="editId" class="input-text" type="text" value="<?php echo $data['id']; ?>"/>
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email"><span><?php  echo __('Email') ?></span></label>
                <div class="control">
                    <input name="email" id="email" title="<?php  echo __('Email') ?>" class="input-text" type="text" data-validate="{required:true}" value="<?php echo $data['email']; ?>"/>
                </div>
            </div>
            <div class="field phone_no">
                <label class="label" for="phone_no"><span><?php  echo __('Contact No') ?></span></label>
                <div class="control">
                    <input name="phone_no" id="phone_no" title="<?php  echo __('Contact No') ?>" class="input-text" type="text" value="<?php echo $data['phone_no']; ?>"/>
                </div>
            </div>
            <div class="field message">
                <label class="label" for="message"><span><?php  echo __('Message') ?></span></label>
                <div class="control">
                    <input name="message" id="message" title="<?php  echo __('Message') ?>" class="input-text" type="text" value="<?php echo $data['message']; ?>"/>
                </div>
            </div>
        </fieldset>
    
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?php  echo __('Save') ?>" class="action submit primary" id="custom_btn">
                    <span><?php  echo __('save') ?></span>
                </button>
            </div>
        </div>
   </form>
</div>