<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin-top: 30px;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    .post-id {
        width: 2%
    }

    .post-name {
        width: 30%
    }
</style>

<table>
    <tr>
        <td><?php echo $block->getStoreName(); ?></td>
    </tr>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Name</th>
        <th>Message</th>
    </tr>
    <?php
    foreach ($block->getPostCollection() as $key => $post) {
        echo '<tr>
                    <td>' . $post->getId() . '</td>
                    <td>' . $post->getName() . '</td>
                    <td>' . $post->getMessage() . '</td>
                  </tr>';
    }
    ?>
</table>

</body>

</html>