<div id="md-knockout-example" data-bind="scope:'md-ko-example'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
    "*":{
            "Magento_Ui/js/core/app": {
                "components": {
                    "md-ko-example": {
                        "component": "Tridhyatech_Knockout/js/mdkojs"
                    }
                }
            }
        }
}
</script>