<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/**
 * @var \Magento\Framework\View\Element\AbstractBlock $block
 */

// We should use strlen function because coupon code could be "0", converted to bool will lead to false
$hasCouponCode = $block->getCouponCode() !== null && strlen($block->getCouponCode()) > 0;
?>
<?php $childBlock = $block->getChildBlock('coupon.child'); ?>
<?php $couponCodes = $childBlock->getCouponCodes(); ?>
<?php $validCoupons = $couponCodes['valid_coupons']; ?>
<?php $invalidCoupons = $couponCodes['invalid_coupons']; ?>
<?php $isModuleEnable = $childBlock->isModuleEnable(); ?>
<?php $couponListType = $childBlock->getCouponListType(); ?>
<?php if (!$isModuleEnable) : ?>
    <div class="block discount" id="block-discount" data-mage-init='{"collapsible":{"active": <?= $hasCouponCode ? 'true' : 'false' ?>, "openedState": "active", "saveState": false}}'>
    <?php endif; ?>
    <?php if (!$isModuleEnable) : ?>
        <div class="title" data-role="title">
            <strong id="block-discount-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Apply Discount Code')) ?></strong>
        </div>
        <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <?php endif; ?>
        <form id="discount-coupon-form" action="<?= $block->escapeUrl($block->getUrl('checkout/cart/couponPost')) ?>" method="post" data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
            <div class="fieldset coupon<?= $hasCouponCode ? ' applied' : '' ?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                <div class="field">
                    <label for="coupon_code" class="label">
                        <span><?= $block->escapeHtml(__('Enter discount code')) ?></span>
                    </label>
                    <div class="control">
                        <input type="text" class="input-text" id="coupon_code" name="coupon_code" value="<?= $block->escapeHtmlAttr($block->getCouponCode()) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Enter discount code')) ?>" <?php if ($hasCouponCode) : ?> disabled="disabled" <?php endif; ?> />
                    </div>
                </div>
                <div class="actions-toolbar">
                    <?php if (!$hasCouponCode) : ?>
                        <div class="primary">
                            <button class="action apply primary" type="button" value="<?= $block->escapeHtmlAttr(__('Apply Discount')) ?>">
                                <span><?= $block->escapeHtml(__('Apply Discount')) ?></span>
                            </button>
                        </div>
                    <?php else : ?>
                        <div class="primary">
                            <button type="button" class="action cancel primary" value="<?= $block->escapeHtmlAttr(__('Cancel Coupon')) ?>">
                                <span><?= $block->escapeHtml(__('Cancel Coupon')) ?></span>
                            </button>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
            <?php if (!$hasCouponCode) : ?>
                <?= /* @noEscape */ $block->getChildHtml('captcha') ?>
            <?php endif; ?>
        </form>
        <?php if ($isModuleEnable && !$hasCouponCode) : ?>
            <div id="coupon-list-content" class="coupon-list-modal-content">
                <div class="coupon-code-content-main">
                    <div>
                        <?php if ($couponListType == '1') : ?>
                            <div class="coupon-code-types-div">
                                <span class="coupon-code-types">Available Coupons</span>
                            </div>
                        <?php endif; ?>
                        <?php foreach ($validCoupons as $coupon) : ?>
                            <div class="coupon-code-main">
                                <div class="coupon-code"><span><?= $block->escapeHtml(__($coupon['coupon_code'])) ?></span></div>
                                <span class="coupon-name"><h4><?= $block->escapeHtml(__($coupon['name'])) ?></h4></span>
                                <p class="coupon-description"><?= $block->escapeHtml(__($coupon['description'])) ?></p>
                                <button type="button" class="action secondory coupon-code-apply-btn" tabindex="0" onclick="coupon.applyCouponCode('<?= $coupon['coupon_code'] ?>')">
                                    <span><?= $block->escapeHtml(__('Apply Coupon')) ?></span>
                                </button>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <?php if ($couponListType == 1) : ?>
                        <div>
                            <div class="coupon-code-types-div">
                                <span class="coupon-code-types">Unavailable Coupons</span>
                            </div>
                            <?php foreach ($invalidCoupons as $coupon) : ?>
                                <div class="coupon-code-main">
                                    <div class="coupon-code"><span><?= $block->escapeHtml(__($coupon['coupon_code'])) ?></span></div>
                                    <span class="coupon-name"><h4><?= $block->escapeHtml(__($coupon['name'])) ?></h4></span>
                                    <p class="coupon-description"><?= $block->escapeHtml(__($coupon['description'])) ?></p>
                                    <button type="button" class="action secondory disabled coupon-code-apply-btn" tabindex="0" onclick="coupon.applyCouponCode('<?= $coupon['coupon_code'] ?>')">
                                        <span><?= $block->escapeHtml(__('Apply Coupon')) ?></span>
                                    </button>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                </div>

            </div>
            <div>
                <a href="#" id="view_coupon_list" onclick="coupon.openCouponModal('<?= $childBlock->getTitle(); ?>','#coupon-list-content')">View Coupon List</a>
            </div>
        <?php endif; ?>
        <?php if (!$isModuleEnable) : ?>
        </div>
    </div>
<?php endif; ?>
<script>
    var coupon;
    require(['jquery', 'couponCode'], function($, couponCode) {
        coupon = couponCode;
    });
</script>