<!-- <div class="example-element" data-mage-init='{"custom_js": {"config":"value1"}}'>A single div 1</div> -->
<br>
<!-- <div class="example-element" data-mage-init='{"Tridhya_JsExample/example": {"config":"value1"}}'>A single div 2</div> -->
<script type="text/x-magento-init">
    {
        "*": {
            "custom_js": {
                "slidername": "Silder Name Here",
                "slideritems": "Silder Items Here"
            },
            "example": {
                "firstname": "Mehul",
                "lastname": "Parmar"
            }
        }
    }
</script>